class CL_EX_BADI_BOOK28 definition
  public
  final
  create public .

*"* public components of class CL_EX_BADI_BOOK28
*"* do not include other source files here!!!
public section.

  interfaces IF_EX_BADI_BOOK28 .
  type-pools SEEX .
protected section.
*"* protected components of class CL_EX_BADI_BOOK28
*"* do not include other source files here!!!
private section.
*"* private components of class CL_EX_BADI_BOOK28
*"* do not include other source files here!!!

  data INSTANCE_BADI_TABLE type SEEX_EXIT_TAB .
ENDCLASS.



CLASS CL_EX_BADI_BOOK28 IMPLEMENTATION.


method IF_EX_BADI_BOOK28~CHANGE_VLINE.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO IF_EX_BADI_BOOK28.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = 'IF_EX_BADI_BOOK28' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = 'IF_EX_BADI_BOOK28'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'ACp8N}yu2aYiIIJTlJK}rG'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->CHANGE_VLINE

       CHANGING
         C_POS = C_POS.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'ACp8N}yu2aYiIIJTlJK}rG'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.


method IF_EX_BADI_BOOK28~OUTPUT.
CLASS CL_EXIT_MASTER DEFINITION LOAD.
DATA: EXIT_OBJ_TAB TYPE SEEX_EXIT_TAB,
      EXIT_OBJ TYPE SEEX_EXIT_TAB_STRUCT.

DATA: EXITINTF TYPE REF TO IF_EX_BADI_BOOK28.


  LOOP AT INSTANCE_BADI_TABLE INTO EXIT_OBJ WHERE
       INTER_NAME = 'IF_EX_BADI_BOOK28' AND
       FLT_VAL    = SPACE.
    APPEND EXIT_OBJ TO EXIT_OBJ_TAB.
  ENDLOOP.

  IF SY-SUBRC = 4.
    CALL METHOD CL_EXIT_MASTER=>CREATE_OBJ_BY_INTERFACE_FILTER
       EXPORTING
          INTER_NAME   = 'IF_EX_BADI_BOOK28'
          FLT_VAL      = SPACE
       IMPORTING
          EXIT_OBJ_TAB = EXIT_OBJ_TAB.

    APPEND LINES OF EXIT_OBJ_TAB TO INSTANCE_BADI_TABLE.
  ENDIF.

  LOOP AT EXIT_OBJ_TAB INTO EXIT_OBJ.

    CHECK NOT EXIT_OBJ-OBJ IS INITIAL.
    CHECK EXIT_OBJ-ACTIVE = SEEX_TRUE.


    EXITINTF ?= EXIT_OBJ-OBJ.

    CALL FUNCTION 'PF_ASTAT_OPEN'
       EXPORTING
           OPENKEY = 'T9p2HcRyaqkjiF8sUz5EH0'
           TYP     = 'UE'.

    CALL METHOD EXITINTF->OUTPUT
       EXPORTING
         I_BOOKING = I_BOOKING.



    CALL FUNCTION 'PF_ASTAT_CLOSE'
       EXPORTING
           OPENKEY = 'T9p2HcRyaqkjiF8sUz5EH0'
           TYP     = 'UE'.

  ENDLOOP.


ENDMETHOD.
ENDCLASS.
