*----------------------------------------------------------------------*
*   INCLUDE  BC405_GDAD_CURSOR_OPTOP                                   *
*----------------------------------------------------------------------*
REPORT  BC405_GDAD_CURSOR_OPTOP.

TYPES:  BEGIN OF LINE_TYPE_SPFLI,
          MANDT  LIKE SPFLI-MANDT,
          CARRID LIKE SPFLI-CARRID,
          CONNID LIKE SPFLI-CONNID,
          CITYFROM LIKE SPFLI-CITYFROM,
          CITYTO LIKE SPFLI-CITYTO,
        END OF LINE_TYPE_SPFLI,

        BEGIN OF LINE_TYPE_SFLIGHT,
          MANDT LIKE SFLIGHT-MANDT,
          CARRID LIKE SFLIGHT-CARRID,
          CONNID LIKE SFLIGHT-CONNID,
          FLDATE LIKE SFLIGHT-FLDATE,
          SEATSMAX LIKE SFLIGHT-SEATSMAX,
          SEATSOCC LIKE SFLIGHT-SEATSOCC,
        END OF LINE_TYPE_SFLIGHT.


DATA: WA_SPFLI TYPE LINE_TYPE_SPFLI.
DATA: WA_SFLIGHT TYPE LINE_TYPE_SFLIGHT,

      ITAB_SPFLI TYPE TABLE OF LINE_TYPE_SPFLI,
      ITAB_SFLIGHT TYPE TABLE OF LINE_TYPE_SFLIGHT.


DATA: C1 TYPE CURSOR, C2 TYPE CURSOR.

SELECT-OPTIONS: SO_CARID FOR WA_SPFLI-CARRID
                DEFAULT 'AA' TO 'LH',
                SO_CONID FOR WA_SPFLI-CONNID.
