*----------------------------------------------------------------------*
*   INCLUDE   BC405_GDAD_NESTED_SELECTSTOP                             *
*----------------------------------------------------------------------*
REPORT  SAPBC405_GDAD_NESTED_SELECTS.

TYPES:  BEGIN OF LINE_TYPE_SPFLI,
          CARRID LIKE SPFLI-CARRID,
          CONNID LIKE SPFLI-CONNID,
          CITYFROM LIKE SPFLI-CITYFROM,
          AIRPFROM LIKE SPFLI-AIRPFROM,
          CITYTO LIKE SPFLI-CITYTO,
          AIRPTO LIKE SPFLI-AIRPTO,
          DEPTIME LIKE SPFLI-DEPTIME,
          ARRTIME LIKE SPFLI-ARRTIME,
        END OF LINE_TYPE_SPFLI,

        BEGIN OF LINE_TYPE_SFLIGHT,
          CARRID LIKE SFLIGHT-CARRID,
          CONNID LIKE SFLIGHT-CONNID,
          FLDATE LIKE SFLIGHT-FLDATE,
          SEATSMAX LIKE SFLIGHT-SEATSMAX,
          SEATSOCC LIKE SFLIGHT-SEATSOCC,
        END OF LINE_TYPE_SFLIGHT,

        BEGIN OF LINE_TYPE_SBOOK,
          BOOKID LIKE SBOOK-BOOKID,
          CUSTOMID LIKE SBOOK-CUSTOMID,
          CUSTTYPE LIKE SBOOK-CUSTTYPE,
          CLASS LIKE SBOOK-CLASS,
        END OF  LINE_TYPE_SBOOK.

DATA: WA_SPFLI TYPE LINE_TYPE_SPFLI,
      WA_SFLIGHT TYPE LINE_TYPE_SFLIGHT,
      WA_SBOOK TYPE LINE_TYPE_SBOOK,

      ITAB_SPFLI TYPE TABLE OF LINE_TYPE_SPFLI,
      ITAB_SFLIGHT TYPE TABLE OF LINE_TYPE_SFLIGHT,
      ITAB_SBOOK TYPE TABLE OF LINE_TYPE_SBOOK.

SELECT-OPTIONS: SO_CITYF FOR WA_SPFLI-CITYFROM NO INTERVALS
                NO-EXTENSION DEFAULT 'FRANKFURT',
                SO_CITYT FOR WA_SPFLI-CITYTO NO INTERVALS
                NO-EXTENSION DEFAULT 'NEW YORK'.
