*----------------------------------------------------------------------*
*   INCLUDE BC405_GDAD_DB_VIEWTOP                                      *
*----------------------------------------------------------------------*
REPORT  SAPBC405GDAD_A_DB_VIEW             .

TYPES: BEGIN OF LINE_TYPE_FLIGHTS,
        CARRID LIKE SCARR-CARRID,
        CARRNAME LIKE SCARR-CARRNAME,
        CONNID LIKE SPFLI-CONNID,
        CITYFROM LIKE SPFLI-CITYFROM,
        CITYTO   LIKE SPFLI-CITYTO,
        FLDATE LIKE SFLIGHT-FLDATE,
        SEATSMAX LIKE SFLIGHT-SEATSMAX,
        SEATSOCC LIKE SFLIGHT-SEATSOCC,
       END OF LINE_TYPE_FLIGHTS.

DATA: WA_FLIGHTS TYPE LINE_TYPE_FLIGHTS.
DATA: ITAB_FLIGHTS TYPE TABLE OF  LINE_TYPE_FLIGHTS.

SELECT-OPTIONS: SO_CITYF FOR WA_FLIGHTS-CITYFROM  NO INTERVALS
                NO-EXTENSION DEFAULT 'FRANKFURT',
                SO_CITYT FOR WA_FLIGHTS-CITYTO  NO INTERVALS
                NO-EXTENSION DEFAULT 'NEW YORK'.
