*----------------------------------------------------------------------*
*   INCLUDE  BC405_GDAD_INNER_JOIN_2TABTOP                             *
*----------------------------------------------------------------------*
REPORT  SAPBC405_GDAD_INNER_JOIN_2TAB.

TYPES: BEGIN OF LINE_TYPE_FLIGHTS,
         CARRID LIKE SPFLI-CARRID,
         CONNID LIKE SPFLI-CONNID,
         CITYFROM LIKE SPFLI-CITYFROM,
         CITYTO LIKE SPFLI-CITYTO,
         FLDATE LIKE SFLIGHT-FLDATE,
         SEATSMAX LIKE SFLIGHT-SEATSMAX,
         SEATSOCC LIKE SFLIGHT-SEATSOCC,
       END OF LINE_TYPE_FLIGHTS.

DATA: WA_FLIGHTS TYPE LINE_TYPE_FLIGHTS.
DATA: ITAB_FLIGHTS TYPE TABLE OF LINE_TYPE_FLIGHTS.

SELECT-OPTIONS: SO_CARR FOR WA_FLIGHTS-CARRID
                NO-EXTENSION DEFAULT 'AA' TO 'LH',
                SO_CONN FOR WA_FLIGHTS-CONNID
                NO-EXTENSION.
