*----------------------------------------------------------------------*
*   INCLUDE BC405_SSCD_SEL_SCREEN_IITOP                               *
*----------------------------------------------------------------------*
REPORT SAPBC405_SSCD_SEL_SCREEN_II NO STANDARD PAGE HEADING.

TYPES: BEGIN OF LINE_TYPE_SFLIGHT,
        CARRID   LIKE SCARR-CARRID,
        CONNID   LIKE SPFLI-CONNID,
        FLDATE   LIKE SFLIGHT-FLDATE,
        SEATSMAX LIKE SFLIGHT-SEATSMAX,
        SEATSOCC LIKE SFLIGHT-SEATSOCC,
       END OF LINE_TYPE_SFLIGHT.

DATA: WA_SFLIGHT TYPE LINE_TYPE_SFLIGHT,
      ITAB_SFLIGHT TYPE STANDARD TABLE OF LINE_TYPE_SFLIGHT.
DATA  FREE_SEATS LIKE WA_SFLIGHT-SEATSMAX.

CONSTANTS MARK VALUE 'X'.
