*&---------------------------------------------------------------------*
*& Modulpool         SAPBC414T_BOOKINGS_06                             *
*&---------------------------------------------------------------------*


INCLUDE bc414T_bookings_06top.
INCLUDE bc414T_bookings_06i01.
INCLUDE bc414T_bookings_06o01.
INCLUDE bc414t_bookings_06f01.
INCLUDE bc414T_bookings_06f02.
INCLUDE bc414T_bookings_06f03.
INCLUDE bc414T_bookings_06f04.
INCLUDE bc414T_bookings_06f05.
INCLUDE bc414t_bookings_06f06.
************************************************************************
* Add include (generated by the change document object BC_BOOK)
* containing the form, which is used to create change documents
************************************************************************
