*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 15.10.1999 at 16:49:08 by user LECHNERI
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LBC43000TOP.                       " Global Data
  INCLUDE LBC43000UXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LBC43000F00                             . " subprograms
  INCLUDE LBC43000I00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LBC43000F...                       " Subprograms
* INCLUDE LBC43000O...                       " PBO-Modules
* INCLUDE LBC43000I...                       " PAI-Modules
