*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 19.11.1997 at 16:15:37 by user SCHREPPM
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LBC430TOP.                         " Global Data
  INCLUDE LBC430UXX.                         " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LBC430F00                               . " subprograms
  INCLUDE LBC430I00                               . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LBC430F...                         " Subprograms
* INCLUDE LBC430O...                         " PBO-Modules
* INCLUDE LBC430I...                         " PAI-Modules
