REPORT CUSBOOK2 .

PARAMETERS: CUSTOMID LIKE SBOOK-CUSTOMID.
TABLES: SCUSTOM, SBOOK, SPFLI.

WRITE: / 'Bestehende Buchungen für Kunde'(001), CUSTOMID,':'.

SELECT * FROM SCUSTOM WHERE ID = CUSTOMID.
  SELECT * FROM SBOOK WHERE CUSTOMID = SCUSTOM-ID.
    SELECT * FROM SPFLI WHERE CARRID = SBOOK-CARRID AND
                            CONNID = SBOOK-CONNID.

  WRITE: / 'Flug'(003), SBOOK-CARRID NO-GAP,
           SBOOK-CONNID NO-ZERO,
           'von'(004), SPFLI-CITYFROM, 'nach'(005),
           SPFLI-CITYTO, 'am'(006), SBOOK-FLDATE.

    ENDSELECT.
  ENDSELECT.
ENDSELECT.

IF SY-SUBRC <> 0.
  WRITE: / 'Keine Buchungen vorhanden!'(002).
ENDIF.
