REPORT CUSBOOK1.

PARAMETERS: CUSTOMID LIKE SBOOK-CUSTOMID.
DATA: BOOKINGS TYPE SCUS_BOOK.

WRITE: / 'Bestehende Buchungen für Kunde'(001), CUSTOMID,':'.

SELECT * FROM SCUS_BOOK INTO BOOKINGS WHERE CUSTOMID = CUSTOMID.

  WRITE: / 'Kunde'(003), BOOKINGS-NAME, 'gebucht auf',
           BOOKINGS-CARRID NO-GAP, BOOKINGS-CONNID NO-ZERO,
           'von'(004), BOOKINGS-CITYFROM, 'nach'(005),
           BOOKINGS-CITYTO, 'am'(006), BOOKINGS-FLDATE.

ENDSELECT.

IF SY-SUBRC <> 0.
  WRITE: / 'Keine Buchungen vorhanden!'(002).
ENDIF.
