*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 01.12.2002 at 16:43:33 by user GOEBEL
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LBC_TAW12_CSS_PDTOP.               " Global Data
  INCLUDE LBC_TAW12_CSS_PDUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LBC_TAW12_CSS_PDF00                     . " subprograms
  INCLUDE LBC_TAW12_CSS_PDI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LBC_TAW12_CSS_PDF...               " Subprograms
* INCLUDE LBC_TAW12_CSS_PDO...               " PBO-Modules
* INCLUDE LBC_TAW12_CSS_PDI...               " PAI-Modules
