INCLUDE mbc_taw12_cst_flighttop.
* Ereignisse
INCLUDE mbc_taw12_cst_flighte01.
* Unterprogramme
INCLUDE mbc_taw12_cst_flightf01.
* PBO-Module
INCLUDE mbc_taw12_cst_flighto01.
* PAI-Module
INCLUDE mbc_taw12_cst_flighti01.
